### ISSUE TITLE
Remove/Centralize Airtable field names

### ISSUE THREAD

**Issue by alexquick** [crownheightsaid/mutual-aid-app#12]
Continued from: https://github.com/crownheightsaid/mutual-aid-app/pull/10#discussion_r401355918

We're trying to come up with a way to avoid a bunch of hard-coded Airtable column name strings. It would be nice if we could come up with a way to do something similar with Airtable select values too.

Maybe we should just KISS and export an object out of the Airtable module?
```
requestFields = {
   requestId: "Request ID",
   status: "Status"
}
. . .  elsewhere . . .
record.get(requestFields.requestId)
```

- If we wanted... the opposite of KISS ... we could play around with wrapping the airtable client to return real types. Right now .find()/select() return Airtable Record instances. We could make a class for each table that maps the fields together and wrap the airtable constructor to have find()/select() return those concrete types correctly. While that does sound like a fun programming exercise I'm not certain it's worth it.

**Comment by mjmaurer** [comment]
Definitely think we should KISS (lol)! after chatting with @mab253, our priorities should be moving fast and have a low barrier to entry
