### ISSUE TITLE
[SMS Pickup] Add remaining fields to DeliveryTable

### ISSUE THREAD

**Issue by piratefsh** [crownheightsaid/mutual-aid-app#138]
Add all fields that appear in the Slack post to DeliveryTable:

-Timeline
-Need
-Description

Parts:
- Add those 3 fields to the delivery-needed/requests.json endpoint:https://github.com/crownheightsaid/mutual-aid-app/blob/cf4ad4938c412b42143e69ffb19bf9e72efe4baf/src/api/delivery-needed/index.js#L63
- Display fields on DeliveryTable only (no need to show in RequestPopup).
  - for Timeline: clarify that it's the timeline set by neighbor and is distinct from DaysOpen
  - for Description:  potentially several lines long, figure out way to display and expand elegantly in table without causing it to be too long

**Comment by mab253** [comment]
the description + longer info could go on a different page maybe, after the "take on this delivery" button ... maybe it's a "see more" button, and the next page could have URL params that feed it data (description, etc.) from the specific request? /request?code=TYHX5G for example ... and the text for "this is what a delivery means, I am sure I can take on this responsibility etc." could also be on that same page ... just a thought!

**Comment by mirandawang** [comment]
:wave: Heya! I'd like to take this on :)
