### ISSUE TITLE
Rename `master` branch to `main`.

### ISSUE THREAD

**Issue by piratefsh** [crownheightsaid/mutual-aid-app#155]
This can happen l[ater this year](https://github.com/github/renaming#later-this-year-seamless-move-for-existing-repositories-) when Github releases tools to make this easier, but I am ticketing so we don't forget.

Considerations:
- communicating this change out to current contributors (via Slack? tagging on GH?)
- the deploy process. afaik Heroku supports pushing to heroku main, so this shouldn't be an issue, but should be tested

**Comment by mab253** [comment]
✊✅ - done!
