### ISSUE TITLE
List more useful information on localhost:3000 

### ISSUE THREAD

**Issue by piratefsh** [crownheightsaid/mutual-aid-app#159]
## Summary
When the webapp gets started up with `npm run local:react`, we are greeted with a blank page that says `Slack attack`. This was because early on in this app the server was primarily a Slack bot. This view is not very useful for new or existing developers.

What could be more useful is a list of all webapp routes (and maybe API routes? open to suggestions) and maybe a link to developing resources. This is not a comprehensive ticket, open to suggestions!

**Comment by jreinlein** [comment]
I'm curious to hear input from someone more familiar with the app and its direction: **how do we feel about adding a navigation element**? I'm not sure how often we expect users to switch between sub-apps (neighbourhood finder, delivery needed, etc?), but having a method of navigation may be helpful if the answer isn't "never" 😅 

Material UI offers a few options, but the ones that make the most sense to me (in desc order) are:
1. [Drawer](https://material-ui.com/components/drawers/)
3. [Breadcrumbs](https://material-ui.com/components/breadcrumbs/)
2. [Tabs](https://material-ui.com/components/tabs/)
4. [Bottom nav](https://material-ui.com/components/bottom-navigation/)

Of course, we could always go with Sher Minn's recommendation and provide links and some copy on the landing page to limit the scope of this piece of work

**Comment by piratefsh** [comment]
completed with #163
