### ISSUE TITLE
Update favicon and description meta

### ISSUE THREAD

**Issue by piratefsh** [crownheightsaid/mutual-aid-app#166]
**First time contributor? Please read https://github.com/crownheightsaid/mutual-aid-app/blob/master/README.md before taking on this ticket.**

## Summary
The webapp currently uses the default favicon and meta description of `create-react-app`. We should update this to avoid potential confusion.

This is how it looks like when it is shared via Slack or other messaging apps: 
<img width="337" alt="Screen Shot 2020-10-23 at 4 37 23 PM" src="https://user-images.githubusercontent.com/1868400/97051935-1c380d80-154e-11eb-95e7-6685c2114892.png">

## Requirements
Current meta description is `Web site created using create-react-app`. 
- Update this to `Crown Heights Mutual Aid web app`

Favicon is curently the React logo
- It should be updated to version seen here: https://crownheightsmutualaid.slack.com/archives/C011CF0SV9D/p1596488091217700?thread_ts=1596420840.208500&cid=C011CF0SV9D, but please confirm with #art_and_design before proceeding.

**Comment by dannysullivan** [comment]
Hi @piratefsh - I'd like to pick up this ticket if it's still up for grabs! Please let me know if someone else wanted it, or if I should just assign myself to it.

**Comment by piratefsh** [comment]
Go for it!
