### ISSUE TITLE
Slack links no longer needed in "Delivery Needed" map

### ISSUE THREAD

**Issue by mab253** [crownheightsaid/mutual-aid-app#186]
Intake volunteers are no longer making Slack posts in the #community_needs channel! The web map is the only method now for listing and picking up deliveries. 

So we no longer need the link back to the Slack post, either in the "Code" column in the web app, or in the pop-up on the map.

<img width="500" alt="Screen Shot 2021-02-23 at 12 25 37 PM" src="https://user-images.githubusercontent.com/17707843/108882329-45d37500-75d2-11eb-8560-104a1f85f8bd.png">
We don't need the link to the Slack post via the neighbor's first name in the pop-up

<img width="500" alt="Screen Shot 2021-02-23 at 12 22 16 PM" src="https://user-images.githubusercontent.com/17707843/108882085-00af4300-75d2-11eb-86e7-3691c8fe9c39.png">
We want to get rid of that red error message

<img width="500" alt="Screen Shot 2021-02-23 at 12 22 36 PM" src="https://user-images.githubusercontent.com/17707843/108882122-0a38ab00-75d2-11eb-860e-384821497e64.png">
And we don't need the link in the "Code" column there

**Comment by caroqliu** [comment]
I'm interested in taking this on!

**Comment by mab253** [comment]
awesome! @caroqliu are you on the Slack? have you done the local dev yet? let me know if you have any q's or need any permissions, help, etc.!
