### ISSUE TITLE
Auto add neighborhood info to airtable

### ISSUE THREAD

**Issue by mjmaurer** [crownheightsaid/mutual-aid-app#24]
This should introduce two new things in the address page:
1. Field for Request Code that should be clearly marked as optional (expects code as in the Requests airtable ex: KSDF)
2. Button at the end for adding the info to the Request airtable

**Comment by mjmaurer** [comment]
This would be the first time were using airtable in browser. If it requires putting api keys in browser, we should instead just create an /api/authed endpoint for intake

**Comment by piratefsh** [comment]
@mjmaurer to clarify, which address page are you referring to? is the the `/neighborhood-finder` or something else?

**Comment by mjmaurer** [comment]
yup `/neighborhood-finder`

**Comment by piratefsh** [comment]
what's the existing auth situation for the app? seems like the /neighborhood-finder page is publicly accessible, do we want to keep it that way? if yes, we can just require auth for this feature.

looked into airtable auth and they do not have oauth2.

**Comment by mjmaurer** [comment]
hmm. I'm sorry I may not have thought this through enough. We agreed to avoid auth if at all possible (I originally implemented slack oauth which felt heavy handed).

Maybe we should make the api endpoint not require auth. It would only be able to update the neighborhood information, and require  the request code to update anything. I think that should be plenty security through obscurity. Let me know your thoughts here!

**Comment by piratefsh** [comment]
@mjmaurer i think should be fine for now!

**Comment by piratefsh** [comment]
so my thought here is to only show the field for request code once the neighbourhood data has been fetched. this should hopefully make it clear that the displayed data will be the one stored to the request.


<img width="586" alt="Screen Shot 2020-04-06 at 2 26 45 PM" src="https://user-images.githubusercontent.com/1868400/78592231-c3539280-7812-11ea-8d5b-c1d8f3cbdf75.png">

**Comment by mjmaurer** [comment]
Love it!
