### ISSUE TITLE
please add some comments to your code

### ISSUE THREAD

**Issue by ericfg** [crownheightsaid/mutual-aid-app#48]
new to javascript, can't make any sense of the code. A few comments to explain what is happening where would make the code much more usable and sharable.

**Comment by piratefsh** [comment]
This is an ongoing effort via PR feedback to ensure any new code is commented. I'll be closing this now as there isn't a specific areas of ask, feel free to reopen or post a new issue and link to parts of code that you think will benefit from comments, happy to work on specific asks.
