### ISSUE TITLE
is this usable outside heroku?

### ISSUE THREAD

**Issue by ericfg** [crownheightsaid/mutual-aid-app#50]
if I want to host this somewhere on a secured server, is that possible?

**Comment by mjmaurer** [comment]
Yup! Heroku is secure, but ultimately this is just an Express Server (served from /index.js) that can be deployed anywhere that has a Node runtime

Here's a guide to deploying an Express server on Azure for instance: https://azure.microsoft.com/en-us/develop/nodejs/

**Comment by ericfg** [comment]
thanks
