### ISSUE TITLE
where are config variables stored?

### ISSUE THREAD

**Issue by ericfg** [crownheightsaid/mutual-aid-app#51]
I'm having trouble getting the mapbox stuff to work, can someone tell me where I'd find the values that were entered in the heroku interface on setup? is that in a file somewhere? in a db? where do I look to make sure it's correct?

**Comment by mjmaurer** [comment]
Where environment variables are stored depends on where the app is deployed.

Assuming Heroku, you can find them at https://dashboard.heroku.com/apps/<your-app>/settings
under "Config Vars"

**Comment by ericfg** [comment]
but where are they "stored"
that's where I can access that data in a GUI, where can I find it / where is it stored?

**Comment by mjmaurer** [comment]
Heroku abstracts that away. To go back to issue #50, renting a VM somewhere and including a `.env` file in the project root would also work as is. (See https://www.npmjs.com/package/dotenv)

If you are interested in Dockerizing this please do!

**Comment by ericfg** [comment]
how would you recommend debugging an error about an invalid api key, when you know that a valid one is there. for me, I'd first validate that it is stored correctly. 
I guess this app for now should be considered heroku only?

**Comment by mjmaurer** [comment]
You mentioned it was a slack key correct? whats the error message? Is it on startup?

I would try running locally for most debug needs (`npm run local:<some-app>`). Check out package.json for what is happening.

**Comment by ericfg** [comment]
in this case it's the mapbox api key 
it builds and deploys fine, just complains about a missing mapbox token
![image](https://user-images.githubusercontent.com/1623830/79798850-8f569200-8327-11ea-9f64-ce41652368ba.png)

**Comment by mjmaurer** [comment]
very odd. And MAPBOX_TOKEN is set? https://github.com/flatbush-united/mutual-aid-app/blob/master/src/webapp/components/QuadrantMap.js#L25

**Comment by ericfg** [comment]
yep. at least as far as the heroku interface says. we've had multiple people try with different valid keys/tokens 
that's why I'm wondering where it is actually stored and how that value is accessed by the function
