### ISSUE TITLE
can't install without slack api key but don't want to set that up until the app is running

### ISSUE THREAD

**Issue by ericfg** [crownheightsaid/mutual-aid-app#52]
it's really awkward to have all variables be required to set this up, don't have a slack info until i connect slack to the app, right? can't install the app without the slack info? 
I used placeholders for most values just to get started.

**Comment by mjmaurer** [comment]
have you pulled the most recent version? you can run without Slack tokens set now (based on your input!)

**Comment by ericfg** [comment]
have not. our crew is still trying to get our heads around heroku and how to deploy changes (we've got a few updates that are stuck in our repo, undeployed)
