### ISSUE TITLE
4-char Request Code has conflicts

### ISSUE THREAD

**Issue by mjmaurer** [crownheightsaid/mutual-aid-app#57]
so we have almost 10000 requests in airtable(!) and we are starting to get overlap with request code. Request code is the last four characters of airtable's unique Id. @mab253  suggested just upping that to last 6 characters. I'm going to look into how this would affect backend, and if we could do this in-place

**Comment by ericfg** [comment]
maybe add in a randomized number before or after? both? just pulling characters from a longer hash is never going to yield unique identifiers
