### ISSUE TITLE
Refactor directory structure

### ISSUE THREAD

**Issue by mjmaurer** [crownheightsaid/mutual-aid-app#6]
Things are starting to settle, and we're sticking with monorepo. Here are proposed changes for the `src/` dir.

- `/webapp`
This stays the same.
- `/slackapp` 
Contains the endpoints that the slack app needs to operate (`interactivity` and `events`)
- `/workers`
Cron-like logic that will be run every X minutes
 - `/api`
Any endpoints we need that may be used by webapp, workers, or slack
- `airtableapi.js`
Shared airtable access with schema
- `slackapi.js`
Helper for Slack web API (https://api.slack.com/methods)
- `constants.js`
Organization names and such
- `middleware.js`
Non slack-only express middleware. Maybe should live in `/api`?
- `index.js`
Unfortunately Create React App needs this here for now

**Comment by alexquick** [comment]
fixed in: https://github.com/crownheightsaid/mutual-aid-app/commit/e506f180c28914d41908a38dd8eea0fc9ed1adcd
