### ISSUE TITLE
Add zone map to app

### ISSUE THREAD

**Issue by mjmaurer** [crownheightsaid/mutual-aid-app#7]
Preferably client side so they can used a cache version of the webapp and it will work if the backend is down

**Comment by mjmaurer** [comment]
It should be added to [this page](crownheightsma.herokuapp.com/neighborhood-finder).

The code for that [page is here](https://github.com/crownheightsaid/mutual-aid-app/blob/master/src/webapp/pages/NeighborhoodFinder.js#L64)!

The geojson for the zone map is here: https://github.com/crownheightsaid/mapbox/blob/master/crownheights-quads.geojson

**Comment by mjmaurer** [comment]
Bonus points if you can add the location to the map when it is entered!

**Comment by piratefsh** [comment]
heck yeah i can take this!

**Comment by mjmaurer** [comment]
lemme know if you need any pointers! I was thinking off to the side for desktop and below for mobile
