### ISSUE TITLE
Create /neighborhood-finder view without header for Airtable block use

### ISSUE THREAD

**Issue by piratefsh** [crownheightsaid/mutual-aid-app#81]
## Problem
The Neighborhood Finder map https://crownheightsma.herokuapp.com/neighborhood-finder is used in the Airtable as a block, which appears as below:

**Initial view**
![Screen Shot 2020-05-29 at 3 55 15 PM](https://user-images.githubusercontent.com/1868400/83299894-07d12e00-a1c5-11ea-90eb-d63b2fdb31e1.png)

Users will have to scroll in that block to see the address field and block. 

**Scrolled down:**
![Screen Shot 2020-05-29 at 3 55 23 PM](https://user-images.githubusercontent.com/1868400/83300138-6f877900-a1c5-11ea-83cd-691b036bb86a.png)

## Suggested solution
Can we create a URL param e.g. ?minimal_view=true that makes the address field and map visible in the Airtable block, and moves it to below the map? For intake volunteers, I don't think it's super important for the title and desc to be visible if they are already familiar with the tool.

## Permissions  needed
- access to intake Airtable, or just create a block with the map in staging Airtable. it should show up the same either way.

**Comment by eldilibra** [comment]
Just to clarify: you'd like to see the address field moved below the map in this case? (It's clear to me to hide the title and the description.)

**Comment by piratefsh** [comment]
@eldilibra good q! the address field should stay above the map! that's where the address is entered by intake volunteers so it shows up on the map. ideally both the map and field can fit within that tiny block.

**Comment by eldilibra** [comment]
I just tried to push my branch to make a PR, but couldn't due to perms. I think I'll have to be made a contributor.

**Comment by eldilibra** [comment]
Here's where I'm at:
![chma-minimal-view](https://user-images.githubusercontent.com/1389505/83311125-4b836200-a1dc-11ea-8337-05933b646457.gif)

Still need to test in Airtable, which may have to happen tomorrow AM.

**Comment by piratefsh** [comment]
@mjmaurer i dont have perms to add contributors, can you help us out here?

**Comment by piratefsh** [comment]
@eldilibra nice, looks good! can you also add a link to the url of the map without minimal view. maybe something like `Need help? See full version of map`. this is just in case if someone stumbles upon minimal view and is confused about what's happening, they can still see the version with the title.

**Comment by eldilibra** [comment]
Good idea, will add tomorrow morning.

**Comment by eldilibra** [comment]
![chma-minimal-view-2](https://user-images.githubusercontent.com/1389505/83333243-8681a600-a26d-11ea-9822-6c10ea08085c.gif)

**Comment by eldilibra** [comment]
I think the next step here is to merge and test on staging (I can't use localhost URLs in Embed blocks on AirTable, apparently).

**Comment by piratefsh** [comment]
sweet, looks great to me! is there a PR out yet? @mjmaurer can you hook @eldilibra with collaborator perms please?

**Comment by eldilibra** [comment]
My changes are ready in a branch, just waiting in permissions to be able to push it and PR

**Comment by mjmaurer** [comment]
Done!

**Comment by eldilibra** [comment]
@mjmaurer it looks like you gave me Triage access, which doesn't allow me to push a branch here. It would let me manage PRs and issues, but not push code. Would you rather I create a fork, then PR from there?

**Comment by mjmaurer** [comment]
Bumped ya up! sorry didn't recognize you from slack :/

**Comment by eldilibra** [comment]
Thanks! PR created: https://github.com/crownheightsaid/mutual-aid-app/pull/82
