### ISSUE TITLE
Register dots on /delivery-needed map as 'clickable'

### ISSUE THREAD

**Issue by mjmaurer** [crownheightsaid/mutual-aid-app#83]
The mouser pointer should change in someway when hovering on dots in https://crownheightsma.herokuapp.com/delivery-needed

**Comment by piratefsh** [comment]
FYI we are using react-mapboxgl so there is an abstraction there. but ultimately what @alex b (they/them) [linked to on Slack](https://docs.mapbox.com/help/tutorials/create-interactive-hover-effects-with-mapbox-gl-js/) will work, which is to set 
  map.getCanvas().style.cursor = 'pointer'
onHover for that particular layer. You can see how onClick is handled here, onHover should be similar. The map object should be available to you in the upper scope from the MapContext

https://github.com/crownheightsaid/mutual-aid-app/blob/master/src/webapp/components/ClusterMapLayers.jsx#L108
