### ISSUE TITLE
Add table view for delivery needed map

### ISSUE THREAD

**Issue by piratefsh** [crownheightsaid/mutual-aid-app#88]
## What
Add a table/list view of requests to https://crownheightsma.herokuapp.com/delivery-needed with the same information available on Slack.

## Why
Delivery Needed Map (DNM) only has a map view right now. This was intended to augment the slack app requests so volunteers can browse for open requests by location.

It would be better to also have a table view of requests so volunteers can do all the browsing on the DNM page. The popovers only show minimal information (first name, x-streets and request code).

They still have to sign up for the request on Slack, but hopefully this makes less back and forth.

## Considerations
- I don't have designs yet, but if you are up for it, you can draft something up
- Hovering/clicking on marker on the map should highlight the table/list entry somehow. And vice versa. Kind of like how the [yelp map view](https://www.yelp.com/search?find_desc=cookies&find_loc=Ditmas+Park%2C+Brooklyn%2C+NY&ns=1) works.
- Add ability to filter and search could be a second iteration feature.
- We average about 30-50 requests so there is no pagination at the moment. Might wanna consider what might happen if we have more requests.

**Comment by allthesignals** [comment]
I'm happy to work on this one!

**Comment by mjmaurer** [comment]
Moving this comment from the PR to the issue:

> I have a bigger ask that would be SUPER useful. would it be possible to sort open requests by time since the slack post? (and also display the lapsed time)
> 
> The message ts field which is used as a thread ID is also a Unix timestamp (https://www.unixtimestamp.com/index.php), so there wouldn't need to be any extra network calls
> 
> This would be a good supplement to #63

**Comment by piratefsh** [comment]
Closed because this was merged
