### ISSUE TITLE
Github webhook that posts to wg_tech for every release.

### ISSUE THREAD

**Issue by mjmaurer** [crownheightsaid/mutual-aid-app#91]
this would be a fun thing to have! I imagine it should also link to CHANGELOG.md so people can easily see what is new.

I believe this is the github webhook we want: https://help.github.com/en/actions/reference/events-that-trigger-workflows#release-event-release (on "created").

The endpoint should live in `src/api/github`

**Comment by wrudebusch** [comment]
@mjmaurer I was going to do this: https://slack.com/help/articles/232289568-GitHub-for-Slack but i need to be a Slack admin to install it.

**Comment by mjmaurer** [comment]
Yup! and could probably used to be updated with new channel names and mappings

**Comment by wrudebusch** [comment]
I think I subscribed to CHMA github using the Slack app. IDK, I guess we'll see. details/config: https://crownheightsmutualaid.slack.com/apps/A8GBNUWU8-github

**Comment by mjmaurer** [comment]
I saw a github permission request for slack. is that related?

**Comment by wrudebusch** [comment]
@mjmaurer yes. it it hooked up?

**Comment by mjmaurer** [comment]
I think it was only enabled for crownheightsaid/website. I just did it for this repo as well so hopefully that will work?

**Comment by wrudebusch** [comment]
i think this is working. Close?
