### ISSUE TITLE
Can't upload receipts with airtable forms on mobile

### ISSUE THREAD

**Issue by mjmaurer** [crownheightsaid/mutual-aid-app#97]
From Slack:

> Hi Tech support! I and one other volunteer noticed that we had issues uploading receipt photos to the reimbursement bot form. When asked to select an image it doesn't link to our camera roles or downloads. We both have Android phones and are wondering if that is the common denominator? I have just emailed my self the photos and then posted the receipt from my computer instead of phone. Any idea as to why this is happening? Thanks!

We should investigate and maybe consider a new solution if its not possible with airtable!

**Comment by wrudebusch** [comment]
Uploads to Airtable forms need to be done in the browser _not_ the official Airtable app. 
For example, here is the staging form: https://airtable.com/shrRt6MnrcuQIq2wT copy&paste into Chrome and it should let you attach a picture. But if you open it in the Airtable app it won't. 

I guess this feature not a big? IDK, but here is the official documentation and current breakdown of functionality: https://support.airtable.com/hc/en-us/articles/217039867-What-are-the-differences-between-the-desktop-and-mobile-versions-of-Airtable-
