### ISSUE TITLE
allow intake volunteers to delete a request and post it again 

### ISSUE THREAD

**Issue by mab253** [crownheightsaid/mutual-aid-app#98]
right now it seems that if an intake volunteer posts in the wrong channel, or they need to start over with a post rather than edit it, the Slack app won't let them delete and re-post. The corresponding code won't appear when they click the lightning bolt to "Post Open Request" - so they only get to post the request once.

** i was able to fix this manually for someone in the Airtable by deleting the slack_ts and slack_channel in the "Meta" field in Airtable ... a good place to start?

**Comment by mjmaurer** [comment]
>  i was able to fix this manually for someone in the Airtable by deleting the slack_ts and slack_channel

if we add as something to do when using `Edit Bot Post > Delete` is that a good solution?
